// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// Placeholder - future optimizations can be added here
// For now, the R implementation is sufficient

// Rcpp init
RcppExport SEXP _rcpp_module_boot_stub() {
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stub", (DL_FUNC) &_rcpp_module_boot_stub, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_scTenifoldKnk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
